[package]
name = "rust_server_app"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3.3.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
sqlite = "0.26.0"
diesel = { version = "1.4.5", features = ["sqlite"] }
dotenv = "0.15.0"

[[bin]]
name = "main"
path = "src/main.rs"