-- This file is auto-generated by Diesel CLI.
-- It will be overwritten by Diesel CLI when you run migrations.

-- Add a comment here to prevent Diesel CLI from overwriting this file.
-- You can also add additional migration setup here.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";